// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * FileChange 表示单个文件的变更记录
 */
export class FileChange {
    "path": string;

    /**
     * add, modify, delete
     */
    "change_type": string;
    "diff"?: string;

    /** Creates a new FileChange instance. */
    constructor($$source: Partial<FileChange> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("change_type" in $$source)) {
            this["change_type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChange instance from a string or object.
     */
    static createFrom($$source: any = {}): FileChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChange($$parsedSource as Partial<FileChange>);
    }
}

/**
 * GraphData 是知识图谱的完整数据
 */
export class GraphData {
    "nodes": KnowledgeNode[];
    "edges": KnowledgeEdge[];

    /** Creates a new GraphData instance. */
    constructor($$source: Partial<GraphData> = {}) {
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphData instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphData {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField1_0($$parsedSource["edges"]);
        }
        return new GraphData($$parsedSource as Partial<GraphData>);
    }
}

/**
 * KnowledgeEdge 是知识图谱中的关系边
 */
export class KnowledgeEdge {
    "source_id": string;
    "target_id": string;

    /**
     * depends_on, implements, relates_to, caused_by
     */
    "relation": string;

    /** Creates a new KnowledgeEdge instance. */
    constructor($$source: Partial<KnowledgeEdge> = {}) {
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }
        if (!("target_id" in $$source)) {
            this["target_id"] = "";
        }
        if (!("relation" in $$source)) {
            this["relation"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnowledgeEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): KnowledgeEdge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KnowledgeEdge($$parsedSource as Partial<KnowledgeEdge>);
    }
}

/**
 * KnowledgeNode 是知识图谱中的节点
 */
export class KnowledgeNode {
    "id": string;
    "label": string;

    /**
     * file, module, decision, concept
     */
    "type": string;
    "metadata": { [_ in string]?: string };

    /** Creates a new KnowledgeNode instance. */
    constructor($$source: Partial<KnowledgeNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnowledgeNode instance from a string or object.
     */
    static createFrom($$source: any = {}): KnowledgeNode {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField3_0($$parsedSource["metadata"]);
        }
        return new KnowledgeNode($$parsedSource as Partial<KnowledgeNode>);
    }
}

/**
 * ProjectSnapshot 表示项目在某一时刻的快照
 */
export class ProjectSnapshot {
    "id": string;
    "timestamp": time$0.Time;
    "version": string;
    "dependencies": string[];
    "metadata": { [_ in string]?: string };

    /** Creates a new ProjectSnapshot instance. */
    constructor($$source: Partial<ProjectSnapshot> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("dependencies" in $$source)) {
            this["dependencies"] = [];
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSnapshot {
        const $$createField3_0 = $$createType5;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dependencies" in $$parsedSource) {
            $$parsedSource["dependencies"] = $$createField3_0($$parsedSource["dependencies"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField4_0($$parsedSource["metadata"]);
        }
        return new ProjectSnapshot($$parsedSource as Partial<ProjectSnapshot>);
    }
}

/**
 * SearchResult 是知识库搜索的返回结果
 */
export class SearchResult {
    "entry": StructuredEntry;
    "score": number;
    "node_path"?: KnowledgeNode[];

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("entry" in $$source)) {
            this["entry"] = (new StructuredEntry());
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField0_0 = $$createType6;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField0_0($$parsedSource["entry"]);
        }
        if ("node_path" in $$parsedSource) {
            $$parsedSource["node_path"] = $$createField2_0($$parsedSource["node_path"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * StructuredEntry 是 AI 提炼后的结构化知识单元
 */
export class StructuredEntry {
    "id": string;
    "timestamp": time$0.Time;
    "session_id": string;

    /**
     * 代码变更概要
     */
    "summary": string;

    /**
     * 设计决策与理由
     */
    "design_decision": string;

    /**
     * 潜在影响面
     */
    "impact_analysis": string;
    "affected_files": FileChange[];
    "tags": string[];

    /** Creates a new StructuredEntry instance. */
    constructor($$source: Partial<StructuredEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("design_decision" in $$source)) {
            this["design_decision"] = "";
        }
        if (!("impact_analysis" in $$source)) {
            this["impact_analysis"] = "";
        }
        if (!("affected_files" in $$source)) {
            this["affected_files"] = [];
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StructuredEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): StructuredEntry {
        const $$createField6_0 = $$createType8;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("affected_files" in $$parsedSource) {
            $$parsedSource["affected_files"] = $$createField6_0($$parsedSource["affected_files"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        return new StructuredEntry($$parsedSource as Partial<StructuredEntry>);
    }
}

// Private type creation functions
const $$createType0 = KnowledgeNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = KnowledgeEdge.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = StructuredEntry.createFrom;
const $$createType7 = FileChange.createFrom;
const $$createType8 = $Create.Array($$createType7);
