// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ProjectConfig 表示一个被监控的项目
 */
export class ProjectConfig {
    "id": string;
    "name": string;
    "path": string;
    "description"?: string;
    "is_active": boolean;
    "created_at": string;

    /** Creates a new ProjectConfig instance. */
    constructor($$source: Partial<ProjectConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("is_active" in $$source)) {
            this["is_active"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectConfig($$parsedSource as Partial<ProjectConfig>);
    }
}
