// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChronoService 提供前端可调用的核心业务方法
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./pkg/models/models.js";

/**
 * AddProject 添加新项目并切换
 */
export function AddProject(name: string, path: string, description: string): $CancellablePromise<config$0.ProjectConfig | null> {
    return $Call.ByID(420626650, name, path, description).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CaptureChanges 前端调用：手动触发变动捕获与索引
 */
export function CaptureChanges(sessionID: string): $CancellablePromise<models$0.StructuredEntry | null> {
    return $Call.ByID(2161555305, sessionID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CreateSnapshot 前端调用：创建项目快照
 */
export function CreateSnapshot(version: string, dependencies: string[]): $CancellablePromise<models$0.ProjectSnapshot | null> {
    return $Call.ByID(2045072130, version, dependencies).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * DetectDependencies 前端调用：检测项目依赖
 */
export function DetectDependencies(): $CancellablePromise<string[]> {
    return $Call.ByID(4264258456).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * FullIndex 前端调用：全量索引项目现有代码
 */
export function FullIndex(): $CancellablePromise<models$0.StructuredEntry | null> {
    return $Call.ByID(1284341273).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GenerateAgentsMD 前端调用：手动生成 AGENTS.md
 */
export function GenerateAgentsMD(): $CancellablePromise<void> {
    return $Call.ByID(3215153182);
}

/**
 * GetCurrentProject 返回当前活跃项目信息
 */
export function GetCurrentProject(): $CancellablePromise<config$0.ProjectConfig | null> {
    return $Call.ByID(2612621340).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetGraphData 前端调用：获取知识图谱数据
 */
export function GetGraphData(limit: number): $CancellablePromise<models$0.GraphData | null> {
    return $Call.ByID(343775598, limit).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetProjectRoot 返回当前项目根目录
 */
export function GetProjectRoot(): $CancellablePromise<string> {
    return $Call.ByID(2640924059);
}

/**
 * IsKnowledgeBaseEmpty 前端调用：检查知识库是否为空
 */
export function IsKnowledgeBaseEmpty(): $CancellablePromise<boolean> {
    return $Call.ByID(1762013908);
}

/**
 * IsWatcherRunning 前端调用：查询监控状态
 */
export function IsWatcherRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(2519807341);
}

/**
 * ListEntries 前端调用：分页列出知识条目
 */
export function ListEntries(offset: number, limit: number): $CancellablePromise<models$0.StructuredEntry[]> {
    return $Call.ByID(932823910, offset, limit).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListProjects 列出所有已配置的项目
 */
export function ListProjects(): $CancellablePromise<config$0.ProjectConfig[]> {
    return $Call.ByID(561904460).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListSnapshots 前端调用：列出所有快照
 */
export function ListSnapshots(): $CancellablePromise<models$0.ProjectSnapshot[]> {
    return $Call.ByID(2973698827).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * RemoveProject 删除项目
 */
export function RemoveProject(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(4203109583, projectID);
}

/**
 * SearchKnowledge 前端调用：搜索知识库
 */
export function SearchKnowledge(query: string, topK: number): $CancellablePromise<models$0.SearchResult[]> {
    return $Call.ByID(2139240054, query, topK).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * StartWatcher 前端调用：启动文件监控
 */
export function StartWatcher(): $CancellablePromise<void> {
    return $Call.ByID(3948577426);
}

/**
 * StopWatcher 前端调用：停止文件监控
 */
export function StopWatcher(): $CancellablePromise<void> {
    return $Call.ByID(1943547986);
}

/**
 * SwitchProject 切换到指定项目
 */
export function SwitchProject(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(2810824499, projectID);
}

// Private type creation functions
const $$createType0 = config$0.ProjectConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.StructuredEntry.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.ProjectSnapshot.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = models$0.GraphData.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType2);
const $$createType10 = $Create.Array($$createType0);
const $$createType11 = $Create.Array($$createType4);
const $$createType12 = models$0.SearchResult.createFrom;
const $$createType13 = $Create.Array($$createType12);
