// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChronoService 提供前端可调用的核心业务方法
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./pkg/models/models.js";

/**
 * CaptureChanges 前端调用：手动触发变动捕获与索引
 */
export function CaptureChanges(sessionID: string): $CancellablePromise<models$0.StructuredEntry | null> {
    return $Call.ByID(2161555305, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateSnapshot 前端调用：创建项目快照
 */
export function CreateSnapshot(version: string, dependencies: string[]): $CancellablePromise<models$0.ProjectSnapshot | null> {
    return $Call.ByID(2045072130, version, dependencies).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetGraphData 前端调用：获取知识图谱数据
 */
export function GetGraphData(limit: number): $CancellablePromise<models$0.GraphData | null> {
    return $Call.ByID(343775598, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetProjectRoot 返回当前项目根目录
 */
export function GetProjectRoot(): $CancellablePromise<string> {
    return $Call.ByID(2640924059);
}

/**
 * ListEntries 前端调用：分页列出知识条目
 */
export function ListEntries(offset: number, limit: number): $CancellablePromise<models$0.StructuredEntry[]> {
    return $Call.ByID(932823910, offset, limit).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListSnapshots 前端调用：列出所有快照
 */
export function ListSnapshots(): $CancellablePromise<models$0.ProjectSnapshot[]> {
    return $Call.ByID(2973698827).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SearchKnowledge 前端调用：搜索知识库
 */
export function SearchKnowledge(query: string, topK: number): $CancellablePromise<models$0.SearchResult[]> {
    return $Call.ByID(2139240054, query, topK).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.StructuredEntry.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.ProjectSnapshot.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.GraphData.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType0);
const $$createType7 = $Create.Array($$createType2);
const $$createType8 = models$0.SearchResult.createFrom;
const $$createType9 = $Create.Array($$createType8);
